name: Pull Request comments test
on:
  push:
    branches: [ github_action_learn ]
  issue_comment:
    types: [created, edited]
    branches: [ github_action_learn ]
jobs:
  Pull-Request-comments:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '@Pull-Request-comments'
          reaction: rocket
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ self.comments }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
